### ISSUE TITLE
Deleting cluster should not launch provisioning jobs.

### ISSUE THREAD

**Issue by dgoodwin** [openshift/cluster-operator#104]
Something appears to be wrong with recent job logic particularly around the area of cluster deletions. Deleting the cluster appears to kick off repeated provision machineset jobs that all fail.

Surfaces using the fake playbook mock pod rather than AWS but situation may be the same there.

Attempting to delete the jobs also leads to them being recreated.

**Comment by staebler** [comment]
@dgoodwin The provision machineset jobs are doing the deprovisions of the machinesets. We do not have a playbook yet for deprovisioning machinesets. Consequently, the deprovision pods are failing. The behavior that you are seeing is what is expected to happen until we have a playbook to call.

As an aside, there is an outstanding issue (#98) to, among other things, implement a backoff between a job failing and a new job being created.
