### ISSUE TITLE
Readme doesn't explain what cluster-operator is

### ISSUE THREAD

**Issue by e-minguez** [openshift/cluster-operator#344]
It would be nice to have a proper description of what 'cluster-operator' is, features, current status, etc. in the repo 'front page' instead build instructions.

**Comment by rohantmp** [comment]
+1

**Comment by dgoodwin** [comment]
Cluster Operator is dead, see openshift/hive for it's successor.

**Comment by alexxa** [comment]
@dgoodwin If a repo is dead, there should be a big bold note about that at the top of Readme.
